In [3]:
# import libraries
import torch
import numpy as np
import matplotlib.pyplot as plt

In [4]:
# Declare a data list
data = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

# Create a tensor from list
tensor_data = torch.tensor(data)

print(tensor_data)
print(type(tensor_data))

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
<class 'torch.Tensor'>


In [5]:
# Declare a numpy array
np_array = np.array(data)

# Create a tensor from numpy
tensor_np = torch.tensor(np_array)

print(tensor_np)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


New Tensors can be created from other Tensors. The new one will keep the <b>shape and dataype</b> from the argument, unless explictly override

In [6]:
# Declare Tensor from tensors

# Declare a tensor of 0s with the same shape as tensor_data
tensor_zeros = torch.zeros_like(tensor_data)
print(f"Zeros Tensor: \n {tensor_zeros} \n")

# Declare a tensor of 1s withe the same shape as tensor_np
tensor_ones = torch.ones_like(tensor_np)
print(f"Ones Tensor: \n {tensor_ones} \n")

# Declare a random tensor with the the same shape as tensor_np
tensor_random = torch.rand_like(tensor_data, dtype = torch.float)
print(f"Random Tensor: \n {tensor_random} \n")


Zeros Tensor: 
 tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]) 

Ones Tensor: 
 tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]) 

Random Tensor: 
 tensor([[0.7911, 0.2080, 0.6961],
        [0.7797, 0.2187, 0.3251],
        [0.6091, 0.0514, 0.1571]]) 



In [9]:
print(f"Shape of tensor: {tensor_random.shape}")
print(f"Datatype of tensor: {tensor_random.dtype}")
print(f"Device tensor is stored on: {tensor_random.device}")

Shape of tensor: torch.Size([3, 3])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


In [23]:
# Input tensor of ones
x = torch.ones(5)
# Expected output tensor
y = torch.zeros(3)

# Weight coefficient
w = torch.randn(5, 3, requires_grad = True)

# bias coefficient
b = torch.rand(3, requires_grad = True)

# activation function. Multiplication between x and w + bias.
z = torch.matmul(x, w) + b

# loss function
loss = torch.nn.functional.binary_cross_entropy_with_logits(z,y)

print('loss:', loss)

loss: tensor(2.1764, grad_fn=<BinaryCrossEntropyWithLogitsBackward0>)


In [14]:
help(torch.nn)

Help on package torch.nn in torch:

NAME
    torch.nn

PACKAGE CONTENTS
    _reduction
    backends (package)
    common_types
    cpp
    functional
    grad
    init
    intrinsic (package)
    modules (package)
    parallel (package)
    parameter
    qat (package)
    quantizable (package)
    quantized (package)
    utils (package)

FUNCTIONS
    factory_kwargs(kwargs)
        Given kwargs, returns a canonicalized dict of factory kwargs that can be directly passed
        to factory functions like torch.empty, or errors if unrecognized kwargs are present.
        
        This function makes it simple to write code like this::
        
            class MyModule(nn.Module):
                def __init__(self, **kwargs):
                    factory_kwargs = torch.nn.factory_kwargs(kwargs)
                    self.weight = Parameter(torch.empty(10, **factory_kwargs))
        
        Why should you use this function instead of just passing `kwargs` along directly?
        
        1.

In [7]:
# Check is mps is working
# import torch
# if torch.backends.mps.is_available():
#     mps_device = torch.device("mps")
#     x = torch.ones(1, device=mps_device)
#     print (x)
# else:
#     print ("MPS device not found.")

# mps turn on the use of GPU on Mac
# if torch.backends.mps.is_available():
#     tensor = tensor_random.to('mps')
#     print(f"Device tensor is stored on: {tensor.device}")

tensor([1.], device='mps:0')
